### ISSUE TITLE
ConnectionStringBuilder does ignore changed  Retry-Strategy (0.6.11)

### ISSUE THREAD

**Issue by wofr** [Azure/azure-event-hubs#151]
Hi!

I do want to set the Retry-strategy to No-Retry.  The constructor of the ConnectionStringbuilder does not allow to set this value.  Therefore you have to use the "setRetryPolicy" methode.

Unfortunatly the "toString" methode does not rebuild the connection string what ends up that the retry-setting got ignored.  Dropping the "setRetryPolicy" in favour of adding this value to the constructor might be the better solution.

See code and output below

` val namespaceName = config.getString("mynamespace.eventhubwriter.eventhub.namespace")
    val eventHubName = config.getString("mynamespace.eventhubwriter.eventhub.myhub")
    val sasKeyName = config.getString("mynamespace.eventhubwriter.eventhub.sasKeyName")
    val sasKey = config.getString("datamover.eventhubwriter.eventhub.sasKey")
    val connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey)
    println("XXX "+connStr.getRetryPolicy)
    println("XXX "+connStr.toString)
    connStr.setRetryPolicy(RetryPolicy.getNoRetry())
    println("YYY "+connStr.getRetryPolicy)
    println("YYY "+connStr.toString)
`
Output 
`XXX Default
XXX Endpoint=amqps://**************;OperationTimeout=PT1M;RetryPolicy=Default
YYY NoRetry
YYY Endpoint=amqps://**************;OperationTimeout=PT1M;RetryPolicy=Default`

**Comment by SreeramGarlapati** [comment]
Fixed this issue in #245.

Since, the typical ConnectionStringBuilder pattern is to create a builder object and keep adding the properties and then eventually invoke toString() - we chose to retain setRetryPolicy() and setOperationTimeout() methods.
The constructor exposed only the bare-minimum set of parameters that a ConnectionString must have - without which the developer could be left confused.
