### ISSUE TITLE
Unable to connect to remote server 

### ISSUE THREAD

**Issue by ChangeTheCode** [Azure/azure-event-hubs#311]
# Azure Event Hubs question
Hi, 

if I try to connect this example (with the EventProcessorHost)  to my Eventhub occur this error:
`Microsoft.WindowsAzure.Storage.StorageException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond` 
or sometimes this: 
`Microsoft.Azure.EventHubs.Processor.EventProcessorConfigurationException occurred
  HResult=0x80131500
  Message=Encountered error while fetching the list of EventHub PartitionIds`

Some guys written the second error something does with the permissions but in my case I use the "RootManageSharedAccessKey" so there are permission to manage the event hub. 

I added the connectionstring to the storage and event hub. Also I created an event hub entities. So actually, I have no idea, why it doesn't work. 

<!-- 
If you have an issue or a feature request for a specific client library, see the following:
* [.NET](https://github.com/azure/azure-event-hubs-dotnet)

**Comment by sethmanheim** [comment]
@ChangeTheCode Try using the fully qualified namespace name, i.e. myNamespace.servicebus.windows.net.

**Comment by ricardo-ponce** [comment]
Seems to be the same issue, I haven't been able to make Event Processor Listener to work, same error messages:

Microsoft.Azure.EventHubs.Processor.EventProcessorConfigurationException: 'Encountered error while fetching the list of EventHub PartitionIds'
Inner Exception
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

I've tried the Listen Policy connectionstring and also the event hub namespace with the RootManageSharedAccessKey connectionstring... same results for both.  

Any clue?

**Comment by ChangeTheCode** [comment]
Hi, 
I don't find an way to get this to work but I found a another way to get it to work. I used this tutorial 
[https://docs.microsoft.com/de-de/azure/event-hubs/event-hubs-dotnet-framework-getstarted-receive-eph](url) 

Maybe it's a solution for you as well.
