### ISSUE TITLE
feature request: ability to use eventhub and blob storage as combination

### ISSUE THREAD

**Issue by stevengonsalvez** [Azure/azure-event-hubs#322]
Event hub currently limits the size of objects to be >256kb - ~1MB. But with a combination of blob storage (writing the data to blob storage and storing the key in event hub as the event) - the same can be achieved but with a bit of wrapping it around in a utility. 

This would be ideal if it is an inherent feature and available on the SDK for eventhub as well.

**Comment by lulzmachine** [comment]
A similar thing is available for the iothub. It's pretty nice. It's basically so that you can upload logs from your iothub devices. You just connect the iothub to a blob storage, and the devices just call a function, and the upload is handled by microsoft and taggade with the deviceId.

But yeah something similar for the event hub would be pretty cool. Some kind of "linked" file or something (just so the message contents don't have to be sent to every event hub listener)

**Comment by sabeegrewal** [comment]
Hey guys, I don't believe this is planned currently. If you're still interested in this feature, please add your thoughts here: https://feedback.azure.com/forums/34192--general-feedback!
